"""
Test MicrobiomeEngine against AGP-like microbiome cohorts (Exp 2 P1 harness).

Mirrors the shape of tests/test_ecological_biotime.py:
  - `compare_single_sample` runs the engine to match one sample's
     post-antibiotic σ-trajectory and reports RMSE / MAE / final-σ error.
  - `run_full_comparison` aggregates per-sample results across the cohort.

If real AGP raw data is vendored to `data/microbiome/otu_table_L6.txt`,
the loader path is used to derive baselines. Otherwise the
`SyntheticMicrobiomeGenerator` (parameterised on AGP/HMP/DIABIMMUNE
marginal distributions) provides ground-truth baselines and recovery
trajectories.

Each "sample" in this harness is operationalized as a baseline gut
microbiome (healthy adult / dysbiotic / infant) plus an associated
post-antibiotic recovery trajectory generated by
`SyntheticMicrobiomeGenerator.generate_antibiotic_perturbed`. The engine
is initialized from the baseline abundance vector, an antibiotic shock
of matched magnitude is applied at t=0, and the engine integrates
forward for 28 days. The engine's σ trajectory is compared against the
generator's σ trajectory on the same time grid.

This is the AGP A1-rung P1 within-substrate fit deliverable. Pre-collapse
behaviour, FMT recovery, and pathogen-fraction dynamics are exercised
elsewhere (see `tests/test_microbiome_real_data.py`, which uses pytest
fixtures for unit-level validation — this harness is its companion CLI).

Usage:
    python3 tests/test_microbiome_p1.py
    python3 tests/test_microbiome_p1.py --sample agp_healthy_0003
    python3 tests/test_microbiome_p1.py --n-samples 100 --quiet
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

# Add project root
sys.path.insert(0, str(Path(__file__).parent.parent))

from ratchet.engines.microbiome import (
    MicrobiomeEngine,
    MicrobiomeParams,
    MicrobiomeShock,
    ShockType,
    create_microbiome_engine,
)
from ratchet.data.microbiome_loader import (
    MicrobiomeSample,
    SyntheticMicrobiomeGenerator,
)


# ─────────────────────────────────────────────────────────────────────────
# Metric + sigma helpers
# ─────────────────────────────────────────────────────────────────────────


def calculate_rmse(empirical: np.ndarray, simulated: np.ndarray) -> float:
    min_len = min(len(empirical), len(simulated))
    if min_len == 0:
        return float("nan")
    return float(np.sqrt(np.mean((empirical[:min_len] - simulated[:min_len]) ** 2)))


def calculate_mae(empirical: np.ndarray, simulated: np.ndarray) -> float:
    min_len = min(len(empirical), len(simulated))
    if min_len == 0:
        return float("nan")
    return float(np.mean(np.abs(empirical[:min_len] - simulated[:min_len])))


def engine_sigma_of(abundances: np.ndarray) -> float:
    """Compute normalized Shannon diversity *the same way the engine does*.

    The synthetic generator stores a separately-drawn `sigma` field that
    does not reflect the actual abundance vector. For an apples-to-apples
    engine-vs-observation comparison we re-compute σ from the abundance
    vector using the engine's convention (H over nonzero / log(n_nonzero)).
    """
    x = abundances[abundances > 1e-10]
    if len(x) == 0:
        return 0.0
    H = -np.sum(x * np.log(x))
    H_max = np.log(len(x)) if len(x) > 1 else 1.0
    return float(H / H_max) if H_max > 0 else 0.0


# Time-grid sampled along the antibiotic recovery curve (days post-shock)
DEFAULT_RECOVERY_DAYS: List[int] = [0, 3, 5, 7, 10, 14, 21, 28]


# ─────────────────────────────────────────────────────────────────────────
# Cohort construction
# ─────────────────────────────────────────────────────────────────────────


def build_synthetic_cohort(
    n_samples: int = 100,
    n_taxa: int = 100,
    healthy_frac: float = 0.6,
    dysbiotic_frac: float = 0.25,
    infant_frac: float = 0.15,
    seed: int = 42,
) -> Dict[str, Dict]:
    """Build a synthetic AGP-like cohort with baseline + recovery trajectory.

    Each entry maps `sample_id -> {baseline, observed_sigma_traj, days,
    shock_magnitude, profile_type, k, sigma_target, rho}`. The recovery
    trajectory is the σ-series across `DEFAULT_RECOVERY_DAYS`, computed
    with `engine_sigma_of` so the engine's prediction can be compared in
    its own σ-convention.
    """
    cohort: Dict[str, Dict] = {}
    base_rng = np.random.default_rng(seed)

    n_healthy = max(1, int(round(healthy_frac * n_samples)))
    n_dysbiotic = max(0, int(round(dysbiotic_frac * n_samples)))
    n_infants = max(0, n_samples - n_healthy - n_dysbiotic)

    def _make_trajectory(g: SyntheticMicrobiomeGenerator, baseline: MicrobiomeSample,
                          days: List[int]) -> np.ndarray:
        traj = []
        for d in days:
            s = g.generate_antibiotic_perturbed(baseline, days_post_antibiotic=d)
            traj.append(engine_sigma_of(s.abundances))
        return np.asarray(traj, dtype=float)

    # Healthy adults
    for i in range(n_healthy):
        sub_seed = int(base_rng.integers(0, 2**31 - 1))
        g = SyntheticMicrobiomeGenerator(seed=sub_seed)
        baseline = g.generate_healthy_adult(n_taxa=n_taxa,
                                            sample_id=f"agp_healthy_{i:04d}")
        days = list(DEFAULT_RECOVERY_DAYS)
        obs = _make_trajectory(g, baseline, days)
        cohort[baseline.sample_id] = {
            "baseline": baseline,
            "observed_sigma_traj": obs,
            "days": days,
            "shock_magnitude": 0.7,
            "profile_type": "healthy_adult",
            "k": baseline.k,
            "sigma_target": baseline.sigma,
            "rho": baseline.rho,
            "seed": sub_seed,
        }

    # Dysbiotic
    for i in range(n_dysbiotic):
        sub_seed = int(base_rng.integers(0, 2**31 - 1))
        g = SyntheticMicrobiomeGenerator(seed=sub_seed)
        severity = float(base_rng.uniform(0.3, 0.8))
        baseline = g.generate_dysbiotic(n_taxa=n_taxa, severity=severity,
                                        sample_id=f"agp_dysbiotic_{i:04d}")
        days = list(DEFAULT_RECOVERY_DAYS)
        obs = _make_trajectory(g, baseline, days)
        cohort[baseline.sample_id] = {
            "baseline": baseline,
            "observed_sigma_traj": obs,
            "days": days,
            "shock_magnitude": 0.5,  # lower since baseline is already perturbed
            "profile_type": "dysbiotic",
            "severity": severity,
            "k": baseline.k,
            "sigma_target": baseline.sigma,
            "rho": baseline.rho,
            "seed": sub_seed,
        }

    # Infants
    for i in range(n_infants):
        sub_seed = int(base_rng.integers(0, 2**31 - 1))
        g = SyntheticMicrobiomeGenerator(seed=sub_seed)
        age = int(base_rng.integers(30, 365))
        baseline = g.generate_infant(age_days=age, n_taxa=n_taxa,
                                     sample_id=f"agp_infant_{i:04d}")
        days = list(DEFAULT_RECOVERY_DAYS)
        obs = _make_trajectory(g, baseline, days)
        cohort[baseline.sample_id] = {
            "baseline": baseline,
            "observed_sigma_traj": obs,
            "days": days,
            "shock_magnitude": 0.6,
            "profile_type": "infant",
            "age_days": age,
            "k": baseline.k,
            "sigma_target": baseline.sigma,
            "rho": baseline.rho,
            "seed": sub_seed,
        }

    return cohort


# ─────────────────────────────────────────────────────────────────────────
# Engine calibration to a single sample
# ─────────────────────────────────────────────────────────────────────────


def _fit_engine_to_sample(
    baseline: MicrobiomeSample,
    seed: int = 42,
) -> MicrobiomeEngine:
    """Configure engine parameters from the baseline sample.

    We match:
      - n_species : number of taxa in the abundance vector
      - decay/generation/strictness : defaults (engine's healthy ranges)
      - collapse thresholds : relaxed enough that a single antibiotic
        shock does not immediately mark the engine collapsed
        (the synthetic baselines have ranked abundances with max ≈ 0.5–0.9,
        which trips the default 0.3 pathogen threshold; we relax to 0.99
        to allow forward simulation of recovery dynamics)
    """
    n_species = int(len(baseline.abundances))

    params = MicrobiomeParams(
        n_species=n_species,
        collapse_diversity_threshold=0.01,
        collapse_pathogen_threshold=0.99,
        default_decay_rate=0.15,
        default_generation_rate=0.5,
        default_strictness=1.0,
        seed=seed,
    )
    engine = create_microbiome_engine(params=params, seed=seed)
    engine.initialize_from_abundances(baseline.abundances, baseline.taxa_ids)
    # Inform get_rho() of the sample's empirical correlation estimate so
    # the per-sample k_eff returned by the engine roughly tracks the
    # sample's k_eff (the engine internally treats rho as a fixed scalar).
    engine._correlation_estimate = float(baseline.rho)
    return engine


def compare_single_sample(
    sample_id: str,
    cohort: Dict[str, Dict],
    engine: Optional[MicrobiomeEngine] = None,
    verbose: bool = True,
    seed: int = 42,
) -> Dict:
    """Compare MicrobiomeEngine to a single microbiome sample's σ-trajectory.

    Returns dict with the keys the P1 harness consumes:
        sample_id, profile_type, k, num_days,
        empirical_rho, simulated_rho, empirical_sigma, simulated_sigma,
        rmse, mae, final_sigma_error, collapsed
    """
    if sample_id not in cohort:
        raise KeyError(f"Sample {sample_id!r} not in cohort")
    entry = cohort[sample_id]
    baseline: MicrobiomeSample = entry["baseline"]
    obs_sigma_traj: np.ndarray = entry["observed_sigma_traj"]
    days: List[int] = entry["days"]
    shock_mag: float = entry["shock_magnitude"]

    if verbose:
        print(f"\n{'=' * 60}")
        print(f"Comparing engine to sample {sample_id}")
        print(f"{'=' * 60}")
        print(f"Empirical (baseline):")
        print(f"  k (taxa)        : {baseline.k}")
        print(f"  rho             : {baseline.rho:.4f}")
        print(f"  sigma (target)  : {baseline.sigma:.4f}")
        print(f"  sigma (engine)  : {engine_sigma_of(baseline.abundances):.4f}")
        print(f"  profile         : {entry.get('profile_type', 'unknown')}")
        print(f"  recovery days   : {days}")

    if engine is None:
        engine = _fit_engine_to_sample(baseline, seed=seed)

    # Apply antibiotic shock at t=0
    shock = MicrobiomeShock(type=ShockType.ANTIBIOTIC_BROAD, magnitude=shock_mag)
    engine.apply_shock(shock)

    # Integrate forward across the full recovery window
    duration = float(max(days)) + 1.0
    df = engine.run(duration=duration, dt=0.5)

    if len(df) < 2 or "time" not in df.columns or "sigma" not in df.columns:
        return {
            "sample_id": sample_id,
            "error": "engine produced no trajectory",
            "rmse": float("nan"),
        }

    sim_sigma_traj = np.interp(np.asarray(days, dtype=float),
                                df["time"].values, df["sigma"].values)

    sigma_rmse = calculate_rmse(obs_sigma_traj, sim_sigma_traj)
    sigma_mae = calculate_mae(obs_sigma_traj, sim_sigma_traj)

    emp_sigma_final = float(obs_sigma_traj[-1])
    sim_sigma_final = float(sim_sigma_traj[-1])
    final_sigma_error = abs(sim_sigma_final - emp_sigma_final)

    emp_rho = float(baseline.rho)
    sim_rho = float(engine.get_rho())

    if verbose:
        print(f"\nSimulated:")
        print(f"  k (taxa)        : {engine.get_k()}")
        print(f"  rho             : {sim_rho:.4f}")
        print(f"  sigma (final)   : {sim_sigma_final:.4f}")
        print(f"  collapsed       : {engine.is_collapsed()}")
        print(f"\nComparison:")
        print(f"  sigma-traj RMSE      : {sigma_rmse:.4f}")
        print(f"  sigma-traj MAE       : {sigma_mae:.4f}")
        print(f"  final sigma error    : {final_sigma_error:.4f}")
        print(f"  observed sigma traj  : "
              f"[{', '.join(f'{v:.3f}' for v in obs_sigma_traj)}]")
        print(f"  simulated sigma traj : "
              f"[{', '.join(f'{v:.3f}' for v in sim_sigma_traj)}]")

    return {
        "sample_id": sample_id,
        "profile_type": entry.get("profile_type", "unknown"),
        "num_days": int(len(days)),
        "k": int(baseline.k),
        "empirical_rho": emp_rho,
        "simulated_rho": sim_rho,
        "rho_error": abs(sim_rho - emp_rho),
        "empirical_sigma": emp_sigma_final,
        "simulated_sigma": sim_sigma_final,
        "final_sigma_error": final_sigma_error,
        "rmse": sigma_rmse,
        "mae": sigma_mae,
        "collapsed": bool(engine.is_collapsed()),
    }


# ─────────────────────────────────────────────────────────────────────────
# Full-comparison driver
# ─────────────────────────────────────────────────────────────────────────


def run_full_comparison(
    n_samples: int = 100,
    verbose: bool = True,
    sample_to_print: int = 4,
    seed: int = 42,
) -> Dict:
    """Run engine-vs-data comparison across the AGP-like cohort.

    Currently uses the synthetic generator (AGP raw data is not vendored
    to disk in this checkout). If/when AGP data is vendored to
    `data/microbiome/otu_table_L6.txt` + `ag-cleaned.txt`, this driver
    will need a small extension to read real samples instead.
    """
    print("=" * 70)
    print("AGP / Microbiome Engine vs Data Comparison")
    print("=" * 70)

    cohort = build_synthetic_cohort(n_samples=n_samples, seed=seed)
    print(f"\nBuilt cohort of {len(cohort)} samples (source: synthetic AGP-like)")
    if len(cohort) == 0:
        print("Empty cohort — cannot run comparison.")
        return {"status": "no_data"}

    per_sample: List[Dict] = []
    for i, sid in enumerate(list(cohort.keys())):
        verbose_this = verbose and (i < sample_to_print)
        comp = compare_single_sample(sid, cohort, verbose=verbose_this,
                                      seed=seed + i)
        per_sample.append(comp)

    rmses = np.array([c["rmse"] for c in per_sample
                       if not np.isnan(c.get("rmse", np.nan))])
    final_errs = np.array([c["final_sigma_error"] for c in per_sample
                           if "final_sigma_error" in c])
    rho_errs = np.array([c["rho_error"] for c in per_sample
                          if "rho_error" in c])

    summary = {
        "source": "synthetic_agp_like",
        "n_samples": len(per_sample),
        "mean_sigma_rmse": float(np.mean(rmses)) if len(rmses) else float("nan"),
        "median_sigma_rmse": float(np.median(rmses)) if len(rmses) else float("nan"),
        "mean_final_sigma_error": float(np.mean(final_errs)) if len(final_errs) else float("nan"),
        "mean_rho_error": float(np.mean(rho_errs)) if len(rho_errs) else float("nan"),
        "per_sample": per_sample,
    }

    print(f"\n{'=' * 70}")
    print("SUMMARY")
    print(f"{'=' * 70}")
    print(f"  Samples                    : {summary['n_samples']}  (source: {summary['source']})")
    print(f"  Mean sigma-trajectory RMSE : {summary['mean_sigma_rmse']:.4f}")
    print(f"  Median sigma-traj   RMSE   : {summary['median_sigma_rmse']:.4f}")
    print(f"  Mean final-sigma error     : {summary['mean_final_sigma_error']:.4f}")
    print(f"  Mean rho error             : {summary['mean_rho_error']:.4f}")

    return summary


# ─────────────────────────────────────────────────────────────────────────
# Variable mapping smoke test
# ─────────────────────────────────────────────────────────────────────────


def test_ratchet_variable_mapping(
    cohort: Dict[str, Dict],
    verbose: bool = True,
) -> Dict:
    """Validate (k, rho, sigma, k_eff) accessors on MicrobiomeSample."""
    if not cohort:
        return {"all_valid": False, "reason": "empty cohort"}

    if verbose:
        print(f"\n{'=' * 60}")
        print("RATCHET Variable Mapping Validation (Microbiome)")
        print(f"{'=' * 60}")

    bad: List[str] = []
    for sid, entry in list(cohort.items())[:5]:
        s: MicrobiomeSample = entry["baseline"]
        k = s.k
        rho = s.rho
        sigma = s.sigma
        f = s.f
        k_eff = s.k_eff
        expected_k_eff = k / (1.0 + rho * (k - 1)) if k > 1 else float(k)
        valid = all([
            k >= 0,
            0.0 <= rho <= 1.0,
            0.0 <= sigma <= 1.0,
            0.0 <= f <= 1.0,
            abs(k_eff - expected_k_eff) < 1e-3,
        ])
        if verbose:
            print(f"  {sid}: k={k:>4d}  rho={rho:.3f}  sigma={sigma:.3f}  "
                  f"f={f:.3f}  k_eff={k_eff:.2f}  valid={valid}")
        if not valid:
            bad.append(sid)

    return {"all_valid": len(bad) == 0, "invalid_samples": bad}


# ─────────────────────────────────────────────────────────────────────────
# CLI entry
# ─────────────────────────────────────────────────────────────────────────


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Compare MicrobiomeEngine to AGP-like microbiome samples"
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true", help="Reduce output verbosity"
    )
    parser.add_argument(
        "--sample", type=str, default=None,
        help="Compare a specific sample by ID"
    )
    parser.add_argument(
        "--n-samples", type=int, default=100,
        help="Number of samples to generate (default 100)"
    )
    parser.add_argument(
        "--seed", type=int, default=42, help="RNG seed for synthetic data + engine init"
    )
    args = parser.parse_args()

    if args.sample:
        cohort = build_synthetic_cohort(n_samples=max(args.n_samples, 10),
                                          seed=args.seed)
        if args.sample in cohort:
            compare_single_sample(args.sample, cohort, verbose=not args.quiet,
                                   seed=args.seed)
        else:
            print(f"Sample {args.sample!r} not found.")
            print(f"Available (first 20): {list(cohort.keys())[:20]}")
    else:
        cohort = build_synthetic_cohort(n_samples=args.n_samples, seed=args.seed)
        mapping = test_ratchet_variable_mapping(cohort, verbose=not args.quiet)
        print(f"\nVariable mapping: {'PASSED' if mapping['all_valid'] else 'FAILED'}")
        run_full_comparison(
            n_samples=args.n_samples,
            verbose=not args.quiet,
            seed=args.seed,
        )
